---
- hosts: localhost
  name: AIQUM GET Clusters
  vars:
    input: &input
      user: "{{ aiqum_username }}"
      password: "{{ aiqum_password }}"
      force_basic_auth: yes
      validate_certs: false
vars_files:
- vars/aiqum.yml

tasks:

- name: AIQUM GET Clusters
  uri:
    url: "{{ api_base_url }}/datacenter/cluster/clusters"
    method: GET
    return_content: yes
    headers:
      accept: application/json
    <<: *login
register: json_response

- name: dump register
  debug:
    msg: "{{ json_response.json }}"
