---
- hosts: localhost
  collections:
    - netapp.ontap
  gather_facts: no
  name: ONTAP Info
  vars:
    input: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  vars_files:
    - standard_platform_vars.yml
    - specific_config_vars.yml
  vars_prompt:
    - name: "netapp_password"
      prompt: "Enter NetApp Admin Password"
      private: yes
  tasks:

  na_ontap_info:
    state: info
    <<: *login
  register: netapp
debug:
  msg: "{{ netapp.ontap_info.cluster_node_info }}"
