---
- hosts: localhost
  collections:
    - netapp.ontap
#  gather_facts: no
  name: ONTAP Info
  vars:
    netapp_hostname: 172.30.16.215
    netapp_username: admin
    input: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  vars_prompt:
    - name: "netapp_password"
      prompt: "Enter NetApp Admin Password"
      private: yes

  tasks:

# Gathers Node information
  - name: Get Ontapi version
    na_ontap_info:
      state: info
      <<: *login
    register: netapp
  - debug:
      msg: "{{ netapp.ontap_info.cluster_node_info }}"

# Get NetApp Info (password auth)
- name: Get Ontapi version
  na_ontap_info:
    state: info
    <<: *login
  register: ontap_info
- debug:
    msg: "{{ ontap_info.ontap_info }}"


# Gathers all info EXCEPT volume an lun
- name: Get Ontapi version
  na_ontap_info:
    state: info
    <<: *login
    gather_subset:
     - "!volume_info"
     - "!lun_info"
  register: ontap_info
- debug:
    msg: "{{ ontap_info.ontap_info }}"
