---
- hosts: localhost
  collections:
    - netapp.ontap
#  gather_facts: no
  name: ONTAP Info
  vars:
    netapp_hostname: 172.30.16.215
    netapp_username: admin
    input: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  vars_prompt:
    - name: "netapp_password"
      prompt: "Enter NetApp Admin Password"
      private: yes

  tasks:

  - name: Get Ontapi version
    na_ontap_info:
    state: info
    <<: *login
    register: netapp

  - debug:
      msg: "{{ netapp.ontap_info.cluster_node_info }}"
