---
- hosts: localhost
  name: AIQUM Get Storage-Providers fileshares
  vars:
    input: &login
      url_username: "{{ aiqum_username }}"
      url_password: "{{ aiqum_password }}"
      validate_certs: false
      force_basic_auth: yes
  vars_files:
  - vars/aiqum_vars.yml
  tasks:

  - name: AIQUM Storage-Providers fileshares
    uri:
      method: GET
      url: "{{ aiqum_endpoint_url }}/storage-provider/file-shares"
      return_content: yes
      headers:
        Accept: application/json
      <<: *login
    register: json_response

  - name: debug registered vars
    debug:
      msg: "{{ json_response.json }}"
