---
- hosts: localhost
  collections:
    - netapp.ontap
  gather_facts: no
  name: Peering Configuration - Cluster and SVM
  vars:
    input: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  vars_files:
    - standard_platform_vars.yml
    - specific_config_vars.yml
  vars_prompt:
    - name: "netapp_password"
      prompt: "Enter NetApp Admin Password"
      private: yes
  tasks:

# ROLE: na_ontap_config_cluster

  - name: Create cluster peer
    na_ontap_cluster_peer:
      state: "{{ state }}"
      source_intercluster_lifs: "{{ source_intercluster_lif }}"
      dest_intercluster_lifs: "{{ dest_intercluster_lif }}"
      passphrase: "{{ passphrase }}"
      dest_hostname: "{{ dest_netapp_hostname }}"
      <<: *login

# Peer SVM

  - name: Source vserver peer create
    na_ontap_vserver_peer:
      state: "{{ state }}"
      peer_vserver: "{{ peer_vserver }}"
      peer_cluster: "{{ peer_cluster }}"
      vserver: "{{ svm }}"
      applications: snapmirror
      dest_hostname: "{{ dest_netapp_hostname }}"
      <<: *login
