---
- hosts: localhost
  gather_facts: no
  name: SnapMirror Configuration
  vars:
    input: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  vars_files:
    - standard_platform_vars.yml
    - specific_config_vars.yml
  vars_prompt:
    - name: "netapp_password"
      prompt: "Enter NetApp Admin Password"
      private: yes
  tasks:

# SnapMirror Configuration

  - name: Create Destination Volume
    na_ontap_volume:
      state: "{{ state }}"
      name: "{{ svm_vol_name }}"
      aggregate_name: "{{ peer_dest_aggregate }}"
      size: "{{ dest_vol_size }}"
      size_unit: "{{ dest_vol_size_units }}"
      type: "{{ vol_sm_type }}"
      space_guarantee: "none"
      vserver: "{{ peer_vserver }}"
      hostname: "{{ dest_netapp_hostname }}"
      <<: *login

# Create a custom Schedule

  - name: Create Custom Job Schedule for SnapMirror
    na_ontap_job_schedule:
      state: "{{ state }}"
      name: "1min"
      job_minutes: -1
      hostname: "{{ dest_netapp_hostname }}"
      <<: *login

# SnapMirror Configuration on Destination

  - name: Create SnapMirror on Destination
    na_ontap_snapmirror:
      state: "{{ state }}"
      source_volume: "{{ svm_vol_name }}"
      destination_volume: "{{ svm_vol_name }}"
      source_vserver: "{{ svm }}"
      destination_vserver: "{{ peer_vserver }}"
      schedule: "1min"
      hostname: "{{ dest_netapp_hostname }}"
      <<: *login

# SWait for SnapMirror to initialize

  - name: sleep for 60 seconds and continue with play
    wait_for: timeout=60
    delegate_to: localhost

# Mount volume(s) on SVM namespace

  - name: Mount volume
    na_ontap_volume:
      state: "{{ state }}"
      name: "{{ svm_vol_name }}"
      junction_path: "/{{ volume_name }}"
      vserver: "{{ peer_vserver }}"
      hostname: "{{ dest_netapp_hostname }}"
      <<: *login
