cluster: dest97

netapp_hostname: 172.30.16.215
netapp_username: admin
# Leave commented out for vars_promtp to work
#netapp_password:

state: present


# System Specific Varibles

###
# Cluster Standard Configuration Varibles (see below)
###

# cluster_mgmt and node_mgmt LIFs will normally be configured during install
# broadcast-domain split on the "MGMT" interfaces to push them from default to MGMT

###
# ROLE Varibles
###

# Cluster setup - Role varibles

license_codes: YVUCRRRRYVHXCFABGAAAAAAAAAAA,SOHOURRRYVHXCFABGAAAAAAAAAAA,KQSRRRRRYVHXCFABGAAAAAAAAAAA,MBXNQRRRYVHXCFABGAAAAAAAAAAA,GUJZTRRRYVHXCFABGAAAAAAAAAAA,OSYVWRRRYVHXCFABGAAAAAAAAAAA,UZLKTRRRYVHXCFABGAAAAAAAAAAA,EJFDVRRRYVHXCFABGAAAAAAAAAAA

motd_mess: |
  ****************************************************************************
  *
  * Welcome \N, today is \d.
  * You are currently logged into Node/SVM; \n.
  * On cluster \C, running \s \r.  Your last login was \L.
  *
  ****************************************************************************

# DNS Settings - Set to overide Standard config
dns_domain: example.local
#dns_servers: "172.30.16.2,8.8.8.8"
dns_servers: "172.30.16.2"     # Helps remove network dependancy

# NTP Server
#ntp_srvr: time.nist.gov
ntp_srvr: us.pool.ntp.org

# Networking Varibles
#ifgrp_ports: "[e0e, e0f]"
ifgrp_ports: "e0e,e0f"
vlan_id: 201

# Configuring Intercluster LIFs for SnapMirror, Cloud Tier, etc.
inters_lif1: 172.30.16.212
inters_lif1_mask: 255.255.255.0
#inters_lif2: 172.30.16.213
#inters_lif2_mask: 255.255.255.0

# Standard Configuration varibles

# Autosupport Configuration
asup_mailhost_ips: 172.30.16.125

# LDAP Configuration
svm_ldap_server_ips: 172.30.16.125


###
# SVM Standard Configuration Varibles
###

# SVM Varibles
svm: destination

svm_aggregate: "{{ cluster }}_01_aggr1"
#svm_aggregate: "{{ cluster }}{{ nodename }}01a_aggr1"
svm_aggr_list:
svm_port: e0c
svm_address: 172.30.16.218
svm_netmask: 255.255.255.0
svm_gateway: 172.30.16.2

svm_dns_domain: "{{ dns_domain }}"
svm_dns_servers: "{{ dns_servers }}"    # BUG: Can't use the cluster DNS servers

svm_root_vol_security: unix
svm_export_policy_name: data

# Export-Policy Management
export_policy_rules_list:
  - { name: 'default', client_match: '172.30.16.130', ro_rule: 'any', rw_rule: 'any', rule_index: '2', super_user_security: 'any' }
  - { name: 'default', client_match: '172.30.16.0/24', ro_rule: 'any', rw_rule: 'none', rule_index: '3', super_user_security: 'none' }
  - { name: 'default', client_match: '0.0.0.0/0', ro_rule: 'any', rw_rule: 'none', rule_index: '3', super_user_security: 'none' }
  - { name: "{{ svm_export_policy_name }}", client_match: '0.0.0.0/0', ro_rule: 'any', rw_rule: 'any', rule_index: '1', super_user_security: 'any' }

###
# SnapMirror Configuration section
###

###
# Ansible-Vault testing varibles
###

# ansible-vault testing varibles

svm_volume_name: svm_test
secret_vol: secret_vol
size: 1
units: gb
vol_type: dp

# Standard Configuration varibles
