---
- hosts: localhost
  name: AIQUM Get Datacenter SVMs
  vars:
    input: &login
      url_username: "{{ aiqum_username }}"
      url_password: "{{ aiqum_password }}"
      validate_certs: false
      force_basic_auth: yes
  vars_files:
  - vars/aiqum_llab_vars.yml
  tasks:

  - name: AIQUM Get Datacenter SVMs
    uri:
      method: GET
      url: "{{ aiqum_endpoint_url }}/datacenter/svm/svms"
      return_content: yes
      headers:
        accept: application/json
      <<: *login
    register: json_response

  - name: debug registered vars
    debug:
      msg: "{{ json_response.json.records }}"
