cluster: source95

netapp_hostname: 172.30.16.210
netapp_username: admin
#netapp_password:

license_codes: YVUCRRRRYVHXCFABGAAAAAAAAAAA,SOHOURRRYVHXCFABGAAAAAAAAAAA,KQSRRRRRYVHXCFABGAAAAAAAAAAA,MBXNQRRRYVHXCFABGAAAAAAAAAAA,GUJZTRRRYVHXCFABGAAAAAAAAAAA,OSYVWRRRYVHXCFABGAAAAAAAAAAA,UZLKTRRRYVHXCFABGAAAAAAAAAAA,EJFDVRRRYVHXCFABGAAAAAAAAAAA

state: present

# Role varibles

motd_mess: |
  ****************************************************************************
  *
  * Welcome \N, today is \d.
  * You are currently logged into Node/SVM; \n.
  * On cluster \C, running \s \r.  Your last login was \L.
  *
  ****************************************************************************

# NTP Server
ntp_srvr: time.nist.gov

# DNS Settings - Set to overide Standard config
dns_domain: example.local
dns_servers: "172.30.16.2,8.8.8.8"
vdns_servers: "172.30.16.2,8.8.8.8"

# Standard Configuration varibles

#timezone Value:
timezone_var: UTC
#timezone:
timezone: "set -privilege diagnostic -confirmation off;timezone -timezone {{ timezone_var }}"

# Configure the service processors.
service_processor:
    - { node: 'newclu01n01a', ip: '10.253.168.110', gw: '10.253.168.1', mask: '255.255.255.0' }
    - { node: 'newclu01n01b', ip: '10.253.168.112', gw: '10.253.168.1', mask: '255.255.255.0' }

# Autosupport Configuration Varibles
# asup_nodename: *
asup_transport: smtp
asup_noteto: admin@example.com
asup_mailhosts: 172.30.16.125
asup_to_addresses: netapp_admin@example.com

# Autosupport - Set TO: and FROM: fields
asup_to: "system node autosupport modify -node * -to admin@example.local"
asup_from: "system node autosupport modify -node * -from vsim@example.local"

# Disable Autosupport Performance data upload
asup_disperf: "system node autosupport modify -node * -perf false"

# Invoke Autosupport
asup_invoke: "system node autosupport invoke -node * -type all"

# Enable discovery tools
cdp: "run -node * options cdpd.enable on"
lldp: "run -node * options lldp.enable on"

###
# Standard Configuration
###

# Rename root aggregate section
aggr_list:
#  - { name: 'aggr0_vsim_95_01', rename: '{nodename_root}' }
  - { name: 'aggr0_source95_01', rename: '{{ cluster }}_01_root' }
#  - { name: 'aggr0', rename: 'aggr0_pilot_prime_01' }
#  - { name: 'aggr0', rename: 'aggr0_vsim_95_01' }
#  - { name: 'aggr0', rename: 'aggr0_vsim_95_01' }

# Rename root volume section
#vol0_list:
#  - { name: 'vol0', rename: '{nodename_root}' }

# Disabling root Aggregate Snapshot Configuration
# Remove Snap Reserve
aggr_sr: "aggr modify -aggregate source95_01_root -percent-snapshot-space 0"

# Disable Snapshot Schedule
aggr_sched: "node run -node * -command snap sched -A source95_01_root 0 0 0"

# Check for snapshots
aggr_snap_list: "node run -node * -command snap list -A"

# Disabling root volume Snapshot Configuration
# Remove Snap Reserve
rootvol_sr: "volume modify -volume vol0 -precent_snapshot_reserve 0"

# Disable Snapshot Schedule
rootvol_sched: "volume modify -volume vol0 -snapshot-policy none"

# Check for snapshots

# Disable SFO autogiveback
autogiveback: "storage failover modify -node * -auto-giveback false"

# Disable SFO autogiveback
sysmgr: "vserver services web modify -name sysmgr -enabled false"

# # #
# Cluster Customer Specific Security settings

# Modify Default Password Security
sec_passwd: "security login role config modify -passwd-alphanum disabled -role admin -vserver {{ cluster }}"
sec_login_reuse: "security login role config modify -role admin -disallowed-reuse 1 -vserver {{ cluster }}"





###
# LDAP
###

###
# SVM LDAP Configuration Varibles
# These are varibles for the commands below
svm_ldap_configname: lab
svm_ldap_server: 172.30.16.226

# These are standard container information
svm_ldap_base_dn: "dc=lab,ou=bu,o=company"
svm_ldap_user_dn: "cn=users,dc=lab,ou=bu,o=company"
svm_ldap_group_dn: "cn=groups,dc=lab,ou=bu,o=company"
svm_ldap_netgroup_dn: "cn=netgroup,dc=lab,ou=bu,o=company"

# LDAP SVM Client-Config
svm_ldap: "vserver services name-service ldap client create -client-config {{ svm_ldap_configname }} -servers {{ svm_ldap_server }} -schema RFC-2307 -port 389 -query-timeout 3 -min-bind-level anonymous -base-dn {{ svm_ldap_base_dn }} -user-dn {{ svm_ldap_user_dn }} -group-dn {{ svm_ldap_group_dn }} -netgroup-dn {{ svm_ldap_netgroup_dn }}  -base-scope subtree -use-start-tls false -session-security none -vserver {{ svm }}"

# LDAP NSS Configuration
svm_nss_list:
  -  "vserver services name-service ns-switch modify -vserver {{ svm }} -database hosts -sources $nsHostSource"
  -  "vserver services name-service ns-switch modify -vserver {{ svm }} -database group -sources $nsGroupSource"
  -  "vserver services name-service ns-switch modify -vserver {{ svm }} -database passwd -sources $nsPasswordSource"
  -  "vserver services name-service ns-switch modify -vserver {{ svm }} -database netgroup -sources $nsNetgroupSource"


###
# SVM Standard Configuration Varibles
###

# SVM Varibles
svm: source
svm_aggregate: aggr1
svm_aggr_list:
svm_port: e0c
svm_address: 172.30.16.213
svm_netmask: 255.255.0.0
svm_gateway: 172.30.16.2

svm_root_vol_security: unix
svm_export_policy_name: data

# ansible-vault testing varibles

svm_volume_name: svm_test
secret_vol: secret_vol
size: 1
units: gb
vol_type: dp

# User and Role Configuration Varibles
role_cmds:
  - { name: 'netapp_harvest', cmddir: 'version', level: 'readonly', svm: '"{{ cluster }}"' }
  - { name: 'netapp_harvest', cmddir: 'cluster identity show', level: 'readonly', svm: '"{{ cluster }}"' }
  - { name: 'netapp_harvest', cmddir: 'cluster show', level: 'readonly', svm: '"{{ cluster }}"' }
  - { name: 'netapp_harvest', cmddir: 'system node show', level: 'readonly', svm: '"{{ cluster }}"' }
  - { name: 'netapp_harvest', cmddir: 'statistics', level: 'readonly', svm: '"{{ cluster }}"' }
  - { name: 'netapp_harvest', cmddir: 'lun show', level: 'readonly', svm: '"{{ cluster }}"' }
  - { name: 'netapp_harvest', cmddir: 'network interface show', level: 'readonly', svm: '"{{ cluster }}"' }
  - { name: 'netapp_harvest', cmddir: 'qos workload show', level: 'readonly', svm: '"{{ cluster }}"' }

user_list:
  - { name: 'netapp_harvest', app: 'ontapi', auth: 'password', role: 'netapp-harvest-role', pass: 'T3mp-p@55', svm: '"{{ cluster }}"' }
  - { name: 'netapp_pse', app: 'ontapi', auth: 'password', role: 'admin', pass: 'T3mp-p@55', svm: '"{{ cluster }}"' }
  - { name: 'netapp_pse', app: 'console', auth: 'password', role: 'admin', pass: 'T3mp-p@55', svm: '"{{ cluster }}"' }
  - { name: 'netapp_pse', app: 'http', auth: 'password', role: 'admin', pass: 'T3mp-p@55', svm: '"{{ cluster }}"' }
  - { name: 'netapp_pse', app: 'service-processor', auth: 'password', role: 'admin', pass: 'T3mp-p@55', svm: '"{{ cluster }}"' }
  - { name: 'netapp_pse', app: 'ssh', auth: 'password', role: 'admin', pass: 'T3mp-p@55', svm: '"{{ cluster }}"' }
  - { name: 'storage_api', app: 'ontapi', auth: 'password', role: 'admin', pass: 'T3mp-p@55', svm: '"{{ cluster }}"' }
  - { name: 'storage_api', app: 'ontapi', auth: 'password', role: 'vsadmin', pass: 'T3mp-p@55', svm: '"{{ svm }}"' }
  - { name: 'snmp', app: 'snmp', auth: 'usm', role: 'readonly', pass: 'T3mp-p@55', svm: '"{{ svm }}"' }
