---
- hosts: localhost
  gather_facts: no
  name: Destination Cluster Config
  vars:
    input: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  vars_files:
    - standard_platform_vars.yml
    - specific_config_vars.yml
  vars_prompt:
    - name: "netapp_password"
      prompt: "Enter NetApp Admin Password"
      private: yes
  tasks:

# ROLE: na_ontap_config_cluster

  - name: Get Ontapi version
    na_ontap_gather_facts:
      state: info
      <<: *login
      ontapi: 32
  - import_role:
      name: na_ontap_cluster_config
    vars:
      <<: *login

# Standard Cluster configuration section

  # Standardize naming and set common root aggr/vol settings
#  - name: rename node
#    na_ontap_node:
#      from_name: "{{ node_from_name }}"
#      name: "{{ cluster }}-prime"
#      <<: *login

  - name: rename root aggregates
    na_ontap_aggregate:
      state: present
      service_state: online
      from_name: "{{ item.name }}"
      name: "{{ item.rename }}"
      <<: *login
    with_items: "{{ aggr_list }}"
