cluster: dest96

netapp_hostname: 172.30.16.215
netapp_username: admin
# Leave commented out for vars_promtp to work
#netapp_password:

state: present

# System Specific Varibles

###
# Cluster Standard Configuration Varibles (see below)
###

# cluster_mgmt and node_mgmt LIFs will normally be configured during install
# broadcast-domain split on the "MGMT" interfaces to push them from default to MGMT


###
# SVM Standard Configuration Varibles
###

# SVM Varibles
svm: destination
#svm_aggregate: aggr1
svm_aggregate: "{{ cluster }}{{ nodename }}01a_aggr1"
svm_aggr_list:
svm_port: a0a
svm_address: 172.30.16.218
svm_netmask: 255.255.0.0
svm_gateway: 172.30.16.2

svm_root_vol_security: unix
svm_export_policy_name: data

# Export-Policy Management
export_policy_rules:
   - { name: 'default', client_match: '172.30.16.130', ro_rule: 'any', rw_rule: 'any', rule_index: '2', super_user_security: 'any' }
   - { name: 'default', client_match: '0.0.0.0/0', ro_rule: 'any', rw_rule: 'none', rule_index: '3', super_user_security: 'none' }
   - { name: "{{ svm_export_policy_name }}", client_match: '0.0.0.0/0', ro_rule: 'any', rw_rule: 'any', rule_index: '1', super_user_security: 'any' }

# ansible-vault testing varibles

svm_volume_name: svm_test
secret_vol: secret_vol
size: 1
units: gb
vol_type: dp

license_codes: YVUCRRRRYVHXCFABGAAAAAAAAAAA,SOHOURRRYVHXCFABGAAAAAAAAAAA,KQSRRRRRYVHXCFABGAAAAAAAAAAA,MBXNQRRRYVHXCFABGAAAAAAAAAAA,GUJZTRRRYVHXCFABGAAAAAAAAAAA,OSYVWRRRYVHXCFABGAAAAAAAAAAA,UZLKTRRRYVHXCFABGAAAAAAAAAAA,EJFDVRRRYVHXCFABGAAAAAAAAAAA


# Role varibles

motd_mess: |
  ****************************************************************************
  *
  * Welcome \N, today is \d.
  * You are currently logged into Node/SVM; \n.
  * On cluster \C, running \s \r.  Your last login was \L.
  *
  ****************************************************************************

# DNS Settings - Set to overide Standard config
dns_domain: example.local
dns_servers: "172.30.16.2,8.8.8.8"
vdns_servers: "172.30.16.2"

# NTP Server
ntp_srvr: time.nist.gov

# Networking Varibles
#ifgrp_ports: "[e0e, e0f]"
ifgrp_ports: "e0e,e0f"
vlan_id: 201

# Standard Configuration varibles

# Configure the service processors.
service_processor:
  - { node: 'newclu01n01a', ip: '10.253.168.110', gw: '10.253.168.1', mask: '255.255.255.0' }
  - { node: 'newclu01n01b', ip: '10.253.168.112', gw: '10.253.168.1', mask: '255.255.255.0' }

###
# Renaming section
###

# Rename node section - Ex: cluster-01 to clusterh01a
nodename: h
node_names:
  - { from_name: "{{ cluster }}-01", name: "{{ cluster }}{{ nodename }}01a" }
#  - { from_name: "{{ cluster }}-02", name: "{{ cluster }}{{ nodename }}01b" }
#  - { from_name: "{{ cluster }}-03", name: "{{ cluster }}{{ nodename }}02a" }
#  - { from_name: "{{ cluster }}-04", name: "{{ cluster }}{{ nodename }}02b" }

# Rename root aggregate section
aggr_list:
  - { name: 'aggr0_{{ cluster }}_01', rename: "{{ cluster }}{{ nodename }}01a_aggr0" }

# Rename root volume section
vol0_list:
  - { name: 'vol0', rename: "{{ cluster }}{{ nodename }}01a_root" }
